name: cd

permissions:
  id-token: write

on:
  release:
    types: [published]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      projectPath: src/CSharp.Mongo.Migration/CSharp.Mongo.Migration.csproj
      configuration: Release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration $configuration /p:Version=${{github.event.release.name}} $projectPath
      - name: Pack
        run: dotnet pack --configuration $configuration --no-build /p:PackageVersion=${{github.event.release.name}} $projectPath --output .
      - name: NuGet Login
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{secrets.NUGET_USER}}
      - name: Push
        run: dotnet nuget push "*.nupkg" --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
