name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
        configuration: Release
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration $configuration
