name: docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      configuration: Release
      framework: netstandard2.1
      projectName: CSharp.Mongo.Migration
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.x
            9.x
      - name: Install tools
        run: dotnet tool install DefaultDocumentation.Console -g
      - name: Build solution
        run: dotnet build --configuration $configuration
      - name: Generate markdown
        run: |
          defaultdocumentation \
            --AssemblyFilePath src/$projectName/bin/$configuration/$framework/$projectName.dll \
            --ConfigurationFilePath ./docsconfig.json \
            --OutputDirectoryPath Documentation \
      - name: Push to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: Documentation
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_REPO_TOKEN }}


      